from __future__ import print_function
import subprocess # for check_call

def yacc(target, source, env):
	assert len(target)==1
	assert len(source)==1
	target_name=str(target[0])
	source_name=str(source[0])
	subprocess.check_call([
		'yacc',
		source_name,
		'-o',
		target_name
		],
	)
	#print('targe is', target_name)
	#print('source is', source_name)
	#print('env is',env)
	return None
yacc_builder=Builder(
	action=yacc,
	suffix='.gen.c',
	src_suffix='.y',
)
# new environment
env=Environment(BUILDERS={}, PROGSUFFIX='.elf')
env.Replace(CCFLAGS="-O2")
env.Append(BUILDERS={ 'Yacc': yacc_builder })
env.Yacc('foo')
env.Program('prog',[ 'main.c', 'foo.gen.c', 'add.c' ])
