from __future__ import print_function
import subprocess # for check_call

def compress(target, source, env):
	assert len(target)==1
	assert len(source)==1
	target_name=str(target[0])
	source_name=str(source[0])
	subprocess.check_call([
		'yui-compressor',
		source_name
		],
		stdout=open(target_name, 'w'),
	)
	#print('targe is', target_name)
	#print('source is', source_name)
	#print('env is',env)
	return None
compress_builder=Builder(
	action=compress,
	suffix='.out',
)
# new environment
env=Environment(BUILDERS={}, PROGSUFFIX='.elf')
env.Append(BUILDERS={ 'Compress': compress_builder })
env.Compress('src/Movies.js')
