from __future__ import print_function
import subprocess # for check_call

def yacc(target, source, env):
	assert len(target)==1
	assert len(source)==1
	target_name=str(target[0])
	source_name=str(source[0])
	subprocess.check_call([
		'yacc',
		source_name
		],
		stdout=open(target_name, 'w'),
	)
	#print('targe is', target_name)
	#print('source is', source_name)
	#print('env is',env)
	return None
yacc_builder=Builder(
	action=yacc,
	suffix='.c',
)
# new environment
env=Environment(BUILDERS={}, PROGSUFFIX='.elf')
env.Replace(CCFLAGS="-O2")
env.Append(BUILDERS={ 'Yacc': yacc_builder })
env.Yacc('foo.y')
env.Program('prog',[ 'main.c', 'foo.c', 'add.c' ])
