from __future__ import print_function

# WARNING: target and source are lists! so you have multiple sources and
# multiple targets
def post_action(target, source, env):
	tgt=','.join([str(x) for x in target])
	src=','.join([str(x) for x in source])
	print('Finished [{0}] from [{1}]'.format(tgt, src))

env=Environment(PROGSUFFIX='.elf')

bin2=env.Program('two.c')
env.AddPostAction(bin2, post_action)

obj=env.Object('one.c')
env.AddPostAction(obj, post_action)
bin=env.Program(obj)
env.AddPostAction(bin, post_action)
