from __future__ import print_function

def post_action(target, source, env):
	print('Finished [%s]' % (','.join([str(x) for x in target])))

env=Environment(PROGSUFFIX='.elf')
obj=env.Object('one.c')
env.AddPostAction(obj, post_action)
bin=env.Program(obj)
env.AddPostAction(bin, post_action)

bin2=env.Program('two.c')
env.AddPostAction(bin2, post_action)
