from __future__ import print_function

def post_action(target, source, env):
	tgt=','.join([str(x) for x in target])
	src=','.join([str(x) for x in source])
	print('Finished [{0}] from [{1}]'.format(tgt, src))
	return None

env=Environment(PROGSUFFIX='.elf')

'''
def replace_old_builder(env, name):
	def new_builder(env, *kargs, **kwargs):
		method=getattr(env, 'Old'+name)
		res=method(env, *kargs, **kwargs)
		env.AddPostAction(res, post_action)
		return res
	env['BUILDERS']['Old'+name]=env['BUILDERS'][name]
	env['BUILDERS'][name]=new_builder

for name in env['BUILDERS'].keys():
	replace_old_builder(env, name)
'''

obj=env.Object(target='one.o', source='one.c')
bin=env.Program(target='one', source=obj)
bin2=env.Program(target='two', source='two.c')
