env = Environment(PROGSUFFIX='.elf')
env.Replace(CCFLAGS="-O2")

'''
env.Append(
	LIBPATH=[ '.' ],
	LIBS=[ 'hello' ],
)
l1=env.SharedLibrary('hello',[ 'hello.c' ])
l2=env.SharedLibrary('goodbye',[ 'goodbye.c' ])
env.Depends(l2, l1)
'''

l1_env=env.Clone()
l1=l1_env.SharedLibrary('hello',[ 'hello.c' ])

l2_env=env.Clone()
l2_env.Append(
	LIBS=[ 'hello' ],
	LIBPATH=[ '.' ],
)
l2=l2_env.SharedLibrary('goodbye',[ 'goodbye.c' ])
l2_env.Depends(l2, l1)
